#cloud-config
packages:
  - mariadb-server

write_files:
  - content: |
      [mysqld]
      bind-address = 0.0.0.0
    path: /etc/mysql/mariadb.conf.d/50-server.cnf

runcmd:
  - sudo systemctl restart mariadb
  - sudo mysql -e "CREATE DATABASE my_database;"
  - sudo mysql -e "CREATE USER 'admin'@'%' IDENTIFIED BY '12345678';"
  - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;"

