#cloud-config
packages:
  - apache2
  - php
  - libapache2-mod-php
  - php-mysql

write_files:
  - content: |
      <!DOCTYPE html>
      <html>
      <body>
        <h1>webserver html</h1>
      </body>
      </html>
    path: /var/www/html/index.html

runcmd:
  - sudo systemctl restart apache2
